<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Brand;
use App\Models\WatchProduct;
use Illuminate\Support\Str;

class WatchSeeder extends Seeder
{
    public function run(): void
    {
        WatchProduct::query()->delete();
        Brand::query()->delete();

        $items = [
            [
                'brand'           => 'Rolex',
                'model'           => 'GMT MASTER-II SPRITE OYSTER (2026)',
                'reference'       => '126720VTNR',
                'sku'             => 'V4D76954',
                'condition'       => 'Never Been Worn',
                'production_year' => 2026,
                'case_size'       => '40mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 3285',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 315000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/rolex-sprite-indonesia-_2_3a4e5004-aba5-4c4d-be95-2841b1e32f45.jpg?v=1788519463',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'DAYTONA BLACK DIAL CERAMIC RING BEZEL (2026)',
                'reference'       => '126500LN',
                'sku'             => '622136Y6-1',
                'condition'       => 'Like New',
                'production_year' => 2026,
                'case_size'       => '40mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 4131',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 555000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/rolex-daytona-godzila-indonesia-_1.jpg?v=1788519348',
            ],
            [
                'brand'           => 'Tudor',
                'model'           => 'PELAGOS FXD BLACK CARBON \'ALINGHI RED BULL\' BLUE DIAL (2025)',
                'reference'       => '25707KN-0001',
                'sku'             => '98925Z1',
                'condition'       => 'Very Mint',
                'production_year' => 2025,
                'case_size'       => '42mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber MT5602',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 50000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/tudor-pelagos-alinghi-red-bull-_1_cb79b463-8f3e-4dd0-8c4d-93370101833d.jpg?v=1788519284',
            ],
            [
                'brand'           => 'Patek Philippe',
                'model'           => 'AQUANAUT 5167A-001 (2021)',
                'reference'       => '5167A-001',
                'sku'             => '7357631',
                'condition'       => 'New Old Stock',
                'production_year' => 2021,
                'case_size'       => '40mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Calibre 324 SC',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 1498000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/PATEKPHILIPPEAQUANAUT-1.jpg?v=1788514897',
            ],
            [
                'brand'           => 'Bell & Ross',
                'model'           => 'BR-05 CHRONO GREEN DIAL (2025)',
                'reference'       => 'BR05C-GN-ST/SST',
                'sku'             => '12104248',
                'condition'       => 'Very Mint',
                'production_year' => 2025,
                'case_size'       => '42mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber BR-CAL.326',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 69800000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/bell-ross-br-05-chrono-green-_1.jpg?v=1788495019',
            ],
            [
                'brand'           => 'Panerai',
                'model'           => 'LUMINOR LOGO 44MM BLACK DIAL PAM 1084 (2021)',
                'reference'       => 'PAM01084',
                'sku'             => 'OP7233PL0097748-1',
                'condition'       => 'Very Mint',
                'production_year' => 2021,
                'case_size'       => '44mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Manual Winding Calibre P.6000',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 65000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/PANERAILUMINOR-1_802232bc-7de5-4840-8682-4700d7e8feca.jpg?v=1788434378',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'YACHT-MASTER 40MM RHODIUM DIAL PLATINUM BEZEL (2021)',
                'reference'       => '126622',
                'sku'             => '073X2578',
                'condition'       => 'Very Mint',
                'production_year' => 2021,
                'case_size'       => '40mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 3235',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 238000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ROLEXYACHT-MASTER-1.jpg?v=1788433970',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'SEA-DWELLER DEEPSEA BLUE MK2 (2020)',
                'reference'       => '126660',
                'sku'             => 'GL307762',
                'condition'       => 'Very Mint',
                'production_year' => 2020,
                'case_size'       => '44mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 3235',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 215000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ROLEXSEA-DWELLERDEEPSEA-1.jpg?v=1788432309',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'RED SEA-DWELLER 43MM (2019)',
                'reference'       => '126600',
                'sku'             => 'A9X41247',
                'condition'       => 'Very Mint',
                'production_year' => 2019,
                'case_size'       => '43mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 3235',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 195000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ROLEXREDSEA-DWELLER-1.jpg?v=1788432128',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'DAYTONA PLATINUM ICE BLUE DIAL (2019)',
                'reference'       => '116506',
                'sku'             => 'CPO-030926-01',
                'condition'       => 'Very Mint',
                'production_year' => 2019,
                'case_size'       => '40mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 4130',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 1650000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ROLEXDAYTONA-1_3dc30505-5677-4be7-b44d-0e5e840097fc.jpg?v=1788425885',
            ],
            [
                'brand'           => 'Swatch X Audemars Piguet',
                'model'           => 'ROYAL POP LAN BA (2026)',
                'reference'       => 'SSX03L100N',
                'sku'             => '13026807843',
                'condition'       => 'Never Been Worn',
                'production_year' => 2026,
                'case_size'       => '40mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Manual Winding Cal. SISTEM51',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 23000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ap-royal-pop-lan-ba-_1_705e9993-9c67-4e29-a5ba-0065d2f41254.jpg?v=1787803106',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'DATEJUST 36MM BLUE DIAMOND DIAL (2022)',
                'reference'       => '126234',
                'sku'             => '844EP871',
                'condition'       => 'Very Mint',
                'production_year' => 2022,
                'case_size'       => '36mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 3235',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 238000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ROLEXDATEJUST36MM-1_b9c188c7-55a6-445b-893a-f1e146ab234f.jpg?v=1788349736',
            ],
            [
                'brand'           => 'Hublot',
                'model'           => 'BIG BANG UNICO BERLUTI ALUMINIO 44MM GREY DIAL JAPAN LIMITED EDITION (2021)',
                'reference'       => '421.NX.0500.VR.JBER21',
                'sku'             => '1582693',
                'condition'       => 'Very Mint',
                'production_year' => 2021,
                'case_size'       => '44mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber HUB1280',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 275000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/HUBLOTBIGBANGUNICO-1.jpg?v=1788349586',
            ],
            [
                'brand'           => 'Hublot',
                'model'           => 'BIG BANG UNICO BERLUTI NERO GRIGIO CERAMIC 44MM JAPAN LIMITED EDITION (2025)',
                'reference'       => '421.CI.0541.VR.JBER24',
                'sku'             => '2107288',
                'condition'       => 'Very Mint',
                'production_year' => 2025,
                'case_size'       => '44mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber HUB1280',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 268000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/HUBLOTBIGBANGUNICOBERLUTI-1.jpg?v=1788346098',
            ],
            [
                'brand'           => 'Hublot',
                'model'           => 'BIG BANG UNICO SANG BLEU 45MM CERAMIC BLUE LIMITED EDITION (2019)',
                'reference'       => '415.EX.7179.VR.MXM19',
                'sku'             => '1345915',
                'condition'       => 'Very Mint',
                'production_year' => 2019,
                'case_size'       => '45mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber HUB1213',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 198000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/HUBLOTBIGBANG-1_1c33a62b-4f09-497d-811a-fb8de95bdd49.jpg?v=1788345662',
            ],
            [
                'brand'           => 'Hublot',
                'model'           => 'CLASSIC FUSION CHRONOGRAPH 45MM BERLUTI SCRITTO ALL BLACK (UNDATED)',
                'reference'       => '521.CM.0500.VR.BER17',
                'sku'             => '1233405',
                'condition'       => 'Mint / Excellent',
                'production_year' => 2024,
                'case_size'       => '45mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber HUB1143',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 178000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/HUBLOTCLASSICFUSION-1.jpg?v=1788345475',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'SUBMARINER DATE 41MM STARBUCKS (2026)',
                'reference'       => '126610LV',
                'sku'             => '4H7D6890 - 2',
                'condition'       => 'Very Mint',
                'production_year' => 2026,
                'case_size'       => '41mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 3235',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 265000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ROLEXSUBMARINER-1_7429c3a3-0b9e-4aa4-9025-cec84b7557d7.jpg?v=1788342055',
            ],
            [
                'brand'           => 'Blancpain',
                'model'           => 'LEMAN ULTRA SLIM WHITE DIAL (WATCH ONLY)',
                'reference'       => '2100-1127-11',
                'sku'             => '2899',
                'condition'       => 'Mint / Excellent',
                'production_year' => 2024,
                'case_size'       => '38mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 11.50',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 68000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/BLANCPAINLEMAN-1.jpg?v=1788335424',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'SUBMARINER DATE 40MM HULK (2015)',
                'reference'       => '116610LV',
                'sku'             => '5692M3J6',
                'condition'       => 'Very Mint',
                'production_year' => 2015,
                'case_size'       => '40mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 3135',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 358000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ROLEXSUBMARINERDATE40MMHULK-1.jpg?v=1788335246',
            ],
            [
                'brand'           => 'Rolex',
                'model'           => 'SUBMARINER DATE 40MM KERMIT \'Y SERIES\' FLAT FOUR BEZEL (WATCH ONLY)',
                'reference'       => '16610LV',
                'sku'             => 'Y966172',
                'condition'       => 'Mint / Excellent',
                'production_year' => 2024,
                'case_size'       => '40mm',
                'case_material'   => 'Luxury Metal',
                'movement'        => 'Automatic Caliber 3135',
                'box_papers'      => 'Full Set (Box & Papers)',
                'price'           => 255000000,
                'currency'        => 'IDR',
                'availability'    => 'AVAILABLE',
                'image_url'       => 'https://cdn.shopify.com/s/files/1/0682/2009/2547/files/ROLEXSUBMARINERDATE-1_3f78d31a-8505-400b-bf64-3ad35ba548c6.jpg?v=1788335017',
            ],
        ];

        foreach ($items as $item) {
            $brandName = trim($item['brand']);
            $brandSlug = Str::slug($brandName);

            $brand = Brand::firstOrCreate(
                ['slug' => $brandSlug],
                ['name' => $brandName]
            );

            WatchProduct::create([
                'brand_id'        => $brand->id,
                'model'           => $item['model'],
                'reference'       => $item['reference'],
                'sku'             => $item['sku'],
                'condition'       => $item['condition'],
                'production_year' => $item['production_year'],
                'case_size'       => $item['case_size'],
                'case_material'   => $item['case_material'],
                'movement'        => $item['movement'],
                'box_papers'      => $item['box_papers'],
                'price'           => $item['price'],
                'currency'        => $item['currency'],
                'availability'    => $item['availability'],
                'image_url'       => $item['image_url'],
            ]);
        }
    }
}
